### PR TITLE
send campaign method

### PR DESCRIPTION
**Pull request by andresrivas1506**

### CODE REVIEW

**Comment by JacobBennett** [comment]
@andresrivas1506 I'll take a look at this tonight. Want to test it out a bit before pulling it in. Thanks for your contribution!

**Comment by andresrivas1506** [comment]
Sure! :+1:

**Comment by apollonin** [comment]
So what about to add this? And please, don't forget to add to composer also :)

**Comment by adaniello** [comment]
:+1:

**Comment by apollonin** [comment]
cool! Waiting for you. That i can make ```composer update```

**Comment by JacobBennett** [comment]
@andresrivas1506 @apollonin @adaniello Should now be available in version 1.3 if you update your composer file. Thanks guys!

**Comment by andresrivas1506** [comment]
Thanks @JacobBennett !

**Pull request merged**
